In [2]:
!pip install -q kagglehub

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "Social_Network_Ads.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "rakeshrau/social-network-ads",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

C:\Users\Arya\OneDrive\Documents\Riya\Machine_Learning\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\Arya\AppData\Local\Temp\ipykernel_17688\2262343093.py:10: DeprecationWarning: load_dataset is deprecated and will be removed in a future version.
  df = kagglehub.load_dataset(

First 5 records:     User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [5]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [6]:
# Null values check
df.isnull().any()

User ID            False
Gender             False
Age                False
EstimatedSalary    False
Purchased          False
dtype: bool

In [7]:
df.drop('User ID', axis=1, inplace=True)

In [8]:
df

     Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [9]:
import pandas as pd

In [10]:
# Converting gender categorical data into dummies (numeric values)
gender_d = pd.get_dummies(df['Gender'], drop_first=True)

In [11]:
gender_d

      Male
0     True
1     True
2    False
3    False
4     True
..     ...
395  False
396   True
397  False
398   True
399  False

[400 rows x 1 columns]

In [12]:
df.drop('Gender', axis=1, inplace=True)

In [13]:
df

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [14]:
df = pd.concat([df, gender_d], axis=1)

In [15]:
df

     Age  EstimatedSalary  Purchased   Male
0     19            19000          0   True
1     35            20000          0   True
2     26            43000          0  False
3     27            57000          0  False
4     19            76000          0   True
..   ...              ...        ...    ...
395   46            41000          1  False
396   51            23000          1   True
397   50            20000          1  False
398   36            33000          0   True
399   49            36000          1  False

[400 rows x 4 columns]

In [16]:
X = df.iloc[:, [0,1,3]]
y = df.iloc[:, 2]

In [17]:
X

     Age  EstimatedSalary   Male
0     19            19000   True
1     35            20000   True
2     26            43000  False
3     27            57000  False
4     19            76000   True
..   ...              ...    ...
395   46            41000  False
396   51            23000   True
397   50            20000  False
398   36            33000   True
399   49            36000  False

[400 rows x 3 columns]

In [18]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [19]:
# Feature Scaling
sc = StandardScaler()
X = sc.fit_transform(X)

In [20]:
X

array([[-1.78179743, -1.49004624,  1.02020406],
       [-0.25358736, -1.46068138,  1.02020406],
       [-1.11320552, -0.78528968, -0.98019606],
       ...,
       [ 1.17910958, -1.46068138, -0.98019606],
       [-0.15807423, -1.07893824,  1.02020406],
       [ 1.08359645, -0.99084367, -0.98019606]], shape=(400, 3))

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

In [22]:
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

In [23]:
y_pred = classifier.predict(X_test)
result = pd.DataFrame({'Actual' : y_test, 'Predicted' : y_pred})
print(result)

     Actual  Predicted
398       0          0
125       0          0
328       1          1
339       1          1
172       0          0
..      ...        ...
91        0          0
322       0          0
248       0          0
186       0          0
395       1          0

[120 rows x 2 columns]

In [24]:
cf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix \n', cf_matrix)

Confusion Matrix
 [[63  9]
 [14 34]]

In [25]:
print('Accuracy of model')
print(accuracy_score(y_test,y_pred) * 100, '%')

Accuracy of model
80.83333333333333 %